### ISSUE TITLE
(Rescinded) Violating TPDb Terms of Service

### ISSUE THREAD

**Issue by tpdb-james** [CollinHeist/TPDbCollectionMaker#1]
Hello,

I'm reaching out on behalf of TPDb and wanted to kindly ask that this repo be taken down as it's in violation of our [Terms of Service](https://theposterdb.com/terms) sections 4, 5, 8, 12, 14, 15, and 17.

We appreciate your cooperation in this matter.

Thanks!

**Comment by bakerboy448** [comment]
just a passerby, but this request seems to be in ~~questionable faith at best~~ objectively bad faith

Re 4 and 5 and actually looks like all of your points.

#4 
> access or search or attempt to access or search the Services by any means (automated or otherwise) other than through our currently available, published interfaces that are provided by TPDb (and only pursuant to those terms and conditions);

#5
> scrape the Services, and particularly scrape User Content from the Services;

by definition the script does not access your services.  It accesses a saved html file that a user provides

this request is as moronic as Google trying to go after the various YouTube download apps.

Also about as intelligent as a request as the state that tried to go after the reporter for "hacking" by viewing the source with end user browser tools. 

It's clear based on this request, the site performance, and the lack of any API, that tpdb's technical knowledge is lacking at best.

perhaps spend time building an API to reduce the site load rather than chasing down GitHub repos of consumers of arbitrary html pages.

**Comment by woofwoof4everyonefoundation** [comment]
Separately, regardless on ones position on TOS, individual in question did not agree to your TOS and, for that simple reason, is not bound by them.

**Comment by tpdb-james** [comment]
First off, my apologies @CollinHeist.

Thanks for pointing that out @bakerboy448. You're correct. The repo doesn't use any automated means to scrape the site and that was an oversight on my part. I will admit that I wasn't fully focused when submitting the issue, as I stepped away before submitting, and this weekend was exceptionally busy. I deeply regret the oversight and will be more diligent in reviewing and double-checking before sending any future requests. 

After looking over the repo carefully, I am going to go ahead and close off the issue as it's out of scope. We've worked with the community on similar repos in the past and without issue.

Once again, I take full responsibility for the oversight and I apologize for any inconvenience it may have caused.

**Comment by CollinHeist** [comment]
@tpdb-james Sorry for the delayed response, I don't check this repo very often.

No harm done, thanks for acknowledging the mistake! Always good to be diligent, and it is obviously not my intention to violate any TOS.

---

Thanks @woofwoof4everyonefoundation and @bakerboy448 for the responses.

**Comment by tpdb-james** [comment]
Oh no worries at all, I totally understand.

My pleasure and thank you for your understanding! It's greatly appreciated 🙂
